spring:
  application:
    name: anyang
  datasource:
    url: jdbc:mysql://localhost:3306/anyangproj?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${PASSWORD:dongyang}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8085

jwt:
  secret: temporary-local-dev-secret-key-change-this-please-32bytes-min
  expiration: 86400000  # 24시간

admin:
  emails: leenayeon0915@gmail.com,
